# Generated by Django 2.0.6 on 2018-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20180615_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_status',
            field=models.CharField(choices=[('EXEUCTING', 'Executing the Action'), ('WAITING', 'Waiting for User Action'), ('ABORTED', 'Aborted the execution'), ('COMPLETED', 'Completed the Action'), ('FAILED', 'Failed to execute'), ('STOPPED', 'Stopped Executing'), ('CREATED', 'Created Action')], default='CREATED', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='flow_status',
            field=models.CharField(choices=[('INPROGRESS', 'Flow under execution'), ('COMPLETED', 'Flow execution completed'), ('CREATED', 'Flow has been created')], default='CREATED', max_length=20, verbose_name='Flow Status'),
        ),
    ]
