# Generated by Django 2.0.6 on 2018-06-15 11:57

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20180523_0655'),
        ('automation', '0003_auto_20180615_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True, help_text='Date on which workflow executed', null=True, verbose_name='Execution date')),
                ('execution_status', models.CharField(choices=[('INPROGRESS', 'Flow under execution'), ('COMPLETED', 'Flow execution completed'), ('STARTED', 'Flow has been started'), ('FAILED', 'Flow execution has failed')], default='STARTED', max_length=20, verbose_name='Flow Status')),
                ('data', django_mysql.models.JSONField(default=dict, null=True)),
                ('current_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_current_action', to='automation.Action', verbose_name='Initial state')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='current_action',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='data',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='store',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.WorkFlow', verbose_name='Workflow'),
        ),
    ]
