# Generated by Django 2.0.6 on 2018-06-15 12:29

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_workflow_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='workflow_diagram',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
