# Generated by Django 2.0.6 on 2018-06-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_workflow_workflow_diagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_status',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='flow_status',
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='current_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_current_action', to='automation.Action', verbose_name='Initial state'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='execution_status',
            field=models.CharField(choices=[('INPROGRESS', 'Flow under execution'), ('COMPLETED', 'Flow execution completed'), ('STARTED', 'Flow has been started'), ('FAILED', 'Flow execution has failed'), ('SUSPENDED', 'Flow execution has suspended')], default='STARTED', max_length=20, verbose_name='Flow Status'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automation.WorkFlow', verbose_name='Workflow'),
        ),
    ]
