# Generated by Django 2.0.6 on 2018-08-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20180523_0655'),
        ('automation', '0008_noderegister'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderegister',
            name='store',
            field=models.ForeignKey(default='a3a802fcc7604a46a49d5c57150d8d99', on_delete=django.db.models.deletion.PROTECT, to='store.Store', verbose_name='Store'),
            preserve_default=False,
        ),
    ]
