# Generated by Django 2.0.6 on 2018-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_noderegister_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderegister',
            name='node_type',
            field=models.CharField(choices=[('Source', 'Souorce Node'), ('Validator', 'Validation Action Execution Node'), ('Condition', 'Condition Node To Execute Validation'), ('Sink', 'Storage Node To Sink Data')], default='Source', max_length=20, verbose_name='Node Type'),
        ),
        migrations.AlterUniqueTogether(
            name='noderegister',
            unique_together={('python_class', 'python_package')},
        ),
    ]
