# Generated by Django 2.0.6 on 2018-08-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_auto_20180814_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='transitions',
        ),
        migrations.RemoveField(
            model_name='action',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='actionclassregister',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actionmodelregister',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='actionmodelregister',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='initial_action',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='store',
        ),
        migrations.RemoveField(
            model_name='workflowexecution',
            name='current_action',
        ),
        migrations.RemoveField(
            model_name='workflowexecution',
            name='store',
        ),
        migrations.RemoveField(
            model_name='workflowexecution',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionClassRegister',
        ),
        migrations.DeleteModel(
            name='ActionModelRegister',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
        migrations.DeleteModel(
            name='WorkFlow',
        ),
        migrations.DeleteModel(
            name='WorkFlowExecution',
        ),
    ]
