# Generated by Django 2.0.6 on 2018-09-12 05:32

import automation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_storecountry'),
        ('automation', '0011_auto_20180824_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(max_length=255, upload_to=automation.models.validator_image_directory_path, verbose_name='Thumbnail')),
                ('name', models.CharField(max_length=30, verbose_name='Catalogue name')),
                ('description', models.CharField(max_length=30, verbose_name='Catalogue description')),
                ('totalRunCount', models.IntegerField(default=0, verbose_name='run count')),
                ('totalFailureCount', models.IntegerField(default=0, verbose_name='failure count')),
                ('workflowFile', models.FileField(upload_to=automation.models.workflow_file_path)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='Store')),
            ],
        ),
    ]
