# Generated by Django 2.0.6 on 2018-11-07 10:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_auto_20180914_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationworkflow',
            name='flowspec',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='noderegister',
            name='node_type',
            field=models.CharField(choices=[('Source', 'Souorce Node'), ('Action', 'Action Execution Node'), ('Condition', 'Condition Node To Execute Validation'), ('Sink', 'Storage Node To Sink Data')], default='Source', max_length=20, verbose_name='Node Type'),
        ),
    ]
